name: manage-azure-policy-62072008
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/ディザスター_リカバリーを構成されていない仮想マシンの監査_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'policies/Synapse_ワークスペースで脆弱性評価を有効にする必要がある_0049a6b3-a662-4f3e-8635-39cf44ace45a/**'
#      - 'policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**'
#      - 'policies/Batch_アカウントでプライベート_エンドポイント接続を有効にする必要がある_009a0c92-f5b4-4776-9b66-4ed2b4775563/**'
#      - 'policies/仮想マシンに対して_Azure_Backup_を有効にする必要がある_013e242c-8828-4970-87b3-ab247555486d/**'
#      - .github/workflows/manage-azure-policy-62072008.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_62072008}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/ディザスター_リカバリーを構成されていない仮想マシンの監査_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          policies/Synapse_ワークスペースで脆弱性評価を有効にする必要がある_0049a6b3-a662-4f3e-8635-39cf44ace45a/**
          policies/SQL_Server_Integration_Services_integration_runtimes_on_Azure_Data_Factory_should_be_joined_to_a_virtual_network_0088bc63-6dee-4a9c-9d29-91cfdc848952/**
          policies/Batch_アカウントでプライベート_エンドポイント接続を有効にする必要がある_009a0c92-f5b4-4776-9b66-4ed2b4775563/**
          policies/仮想マシンに対して_Azure_Backup_を有効にする必要がある_013e242c-8828-4970-87b3-ab247555486d/**
